jobs:
- job: build_all_linux
  displayName: Build all tasks (Linux)
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: 3.1.102
  - script: bash scripts/install_protobuf.sh
  - script: bash scripts/download_binary.sh
  - script: bash build.sh --target=Build --configuration=Release
    displayName: 'Build with debug'
  - script: find ./ -name AElf.Benchmark.dll
  - script: bash build.sh --target=benchmark --benchmarktest=BlockchainStateMergingTests
  # - task: PublishTestResults@2
  #   condition: always()
  #   inputs:
  #     testRunner: VSTest
  #     testResultsFiles: '**/*.trx'
